-- CreateTable
CREATE TABLE "Template" (
    "id" TEXT NOT NULL,
    "chave" TEXT NOT NULL,
    "nome" TEXT NOT NULL,
    "paraQuem" TEXT NOT NULL,
    "descricao" TEXT NOT NULL,
    "segmentos" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "receita" JSONB NOT NULL,
    "ativo" BOOLEAN NOT NULL DEFAULT true,
    "ordem" INTEGER NOT NULL DEFAULT 0,
    "acesso" TEXT NOT NULL DEFAULT 'gratis',
    "planos" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "precoCentavos" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Template_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TemplateCompra" (
    "id" TEXT NOT NULL,
    "templateId" TEXT NOT NULL,
    "storeId" TEXT NOT NULL,
    "valorCentavos" INTEGER NOT NULL DEFAULT 0,
    "origem" TEXT NOT NULL DEFAULT 'compra',
    "mpPaymentId" TEXT,
    "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TemplateCompra_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Template_chave_key" ON "Template"("chave");

-- CreateIndex
CREATE INDEX "TemplateCompra_storeId_idx" ON "TemplateCompra"("storeId");

-- CreateIndex
CREATE UNIQUE INDEX "TemplateCompra_templateId_storeId_key" ON "TemplateCompra"("templateId", "storeId");

-- AddForeignKey
ALTER TABLE "TemplateCompra" ADD CONSTRAINT "TemplateCompra_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "Template"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TemplateCompra" ADD CONSTRAINT "TemplateCompra_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Templates que vêm com a plataforma (prisma/templates-iniciais.json)
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-essencial', 'essencial', 'Essencial', 'Variedades, perfumaria, loja geral', 'Limpo e direto: busca em destaque, categorias com foto e cartões leves.', ARRAY['geral']::TEXT[], '{"fundo":"#ffffff","superficie":"#ffffff","texto":"#171a1f","textoSuave":"#4a5560","linha":"#d9dde3","corCartao":"#ffffff","escuro":false,"faixa":"loja","banner":"caixa","cartao":"simples","cantos":"suaves","tituloCaixa":"normal","tituloPeso":600,"tituloAlinhamento":"esquerda","nomeProduto":"normal","precoNaCor":false,"precoFonteTitulo":false,"fonte":null,"foto":null,"colunas":6,"compraRapida":"passar-mouse"}'::jsonb, true, 10, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-boutique', 'boutique', 'Boutique', 'Moda, acessórios, beleza, joias', 'Editorial: banner de ponta a ponta, títulos com serifa, fotos altas e muito respiro.', ARRAY['moda', 'beleza']::TEXT[], '{"fundo":"#fbf8f4","superficie":"#fbf8f4","texto":"#1c1917","textoSuave":"#57534e","linha":"#e7e0d8","corCartao":"#efe9e2","escuro":false,"faixa":"loja","banner":"cheio","cartao":"simples","cantos":"retos","tituloCaixa":"normal","tituloPeso":500,"tituloAlinhamento":"esquerda","nomeProduto":"normal","precoNaCor":false,"precoFonteTitulo":false,"fonte":"elegante","foto":"alto","colunas":4,"compraRapida":"passar-mouse"}'::jsonb, true, 20, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-tech', 'tech', 'Tech', 'Eletrônicos, celulares, games, informática', 'Fundo escuro, cartões com contorno, preço em destaque e foto quadrada.', ARRAY['eletronicos']::TEXT[], '{"fundo":"#0b1016","superficie":"#11171f","texto":"#e8edf3","textoSuave":"#98a4b3","linha":"#263243","corCartao":"#151c26","escuro":true,"faixa":"destaque","banner":"caixa","cartao":"contorno","cantos":"suaves","tituloCaixa":"normal","tituloPeso":700,"tituloAlinhamento":"esquerda","nomeProduto":"normal","precoNaCor":true,"precoFonteTitulo":false,"fonte":"moderna","foto":"quadrado","colunas":5,"compraRapida":"passar-mouse"}'::jsonb, true, 30, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-street', 'street', 'Street', 'Streetwear, suplementos, fitness', 'Títulos pesados em caixa alta, faixa preta, cantos retos e banner de ponta a ponta.', ARRAY['esporte', 'moda']::TEXT[], '{"fundo":"#ffffff","superficie":"#ffffff","texto":"#171a1f","textoSuave":"#4a5560","linha":"#0a0a0a","corCartao":"#ececec","escuro":false,"faixa":"preta","banner":"cheio","cartao":"simples","cantos":"retos","tituloCaixa":"alta","tituloPeso":400,"tituloAlinhamento":"esquerda","nomeProduto":"caixa-alta","precoNaCor":false,"precoFonteTitulo":true,"fonte":"impacto","foto":"quadrado","colunas":4,"compraRapida":"passar-mouse"}'::jsonb, true, 40, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-mercado', 'mercado', 'Mercado', 'Mercadinho, conveniência, hortifrúti, delivery', 'Prático e denso: preço grande, botão de comprar sempre à vista e muitos produtos por linha.', ARRAY['alimentos', 'geral']::TEXT[], '{"fundo":"#f4f6f3","superficie":"#ffffff","texto":"#14201a","textoSuave":"#4b5a52","linha":"#dfe6e1","corCartao":"#ffffff","escuro":false,"faixa":"destaque","banner":"caixa","cartao":"preenchido","cantos":"suaves","tituloCaixa":"normal","tituloPeso":700,"tituloAlinhamento":"esquerda","nomeProduto":"normal","precoNaCor":true,"precoFonteTitulo":false,"fonte":"amigavel","foto":"quadrado","colunas":6,"compraRapida":"sempre"}'::jsonb, true, 50, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-pet', 'pet', 'Pet', 'Pet shop, rações, acessórios para pets', 'Alegre e arredondado: fundo creme, cantos bem redondos e fonte amigável.', ARRAY['pet']::TEXT[], '{"fundo":"#fff8ef","superficie":"#fffdf9","texto":"#2b2118","textoSuave":"#6b5a4a","linha":"#f0e3d2","corCartao":"#ffffff","escuro":false,"faixa":"destaque","banner":"caixa","cartao":"preenchido","cantos":"redondos","tituloCaixa":"normal","tituloPeso":700,"tituloAlinhamento":"esquerda","nomeProduto":"normal","precoNaCor":true,"precoFonteTitulo":false,"fonte":"amigavel","foto":"quadrado","colunas":5,"compraRapida":"sempre"}'::jsonb, true, 60, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-gourmet', 'gourmet', 'Gourmet', 'Doces, cafés, comida artesanal, bebidas', 'Tons quentes, títulos com serifa e fotos quadradas que valorizam o produto.', ARRAY['alimentos']::TEXT[], '{"fundo":"#faf5ee","superficie":"#fffaf3","texto":"#2a1d14","textoSuave":"#6e5a49","linha":"#eadccb","corCartao":"#f3e9dc","escuro":false,"faixa":"loja","banner":"caixa","cartao":"simples","cantos":"suaves","tituloCaixa":"normal","tituloPeso":600,"tituloAlinhamento":"esquerda","nomeProduto":"normal","precoNaCor":false,"precoFonteTitulo":false,"fonte":"elegante","foto":"quadrado","colunas":4,"compraRapida":"passar-mouse"}'::jsonb, true, 70, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-atelie', 'atelie', 'Ateliê', 'Artesanato, decoração, papelaria, produtos autorais', 'Minimalista: muito branco, títulos leves e centralizados, poucos produtos por linha.', ARRAY['casa', 'geral']::TEXT[], '{"fundo":"#ffffff","superficie":"#ffffff","texto":"#222222","textoSuave":"#6b6b6b","linha":"#ececec","corCartao":"#f5f5f3","escuro":false,"faixa":"loja","banner":"cheio","cartao":"simples","cantos":"retos","tituloCaixa":"normal","tituloPeso":400,"tituloAlinhamento":"centro","nomeProduto":"normal","precoNaCor":false,"precoFonteTitulo":false,"fonte":"moderna","foto":"retrato","colunas":3,"compraRapida":"passar-mouse"}'::jsonb, true, 80, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-beauty', 'beauty', 'Beauty', 'Cosméticos, skincare, perfumaria', 'Suave e rosado, cartões preenchidos e cantos redondos.', ARRAY['beleza']::TEXT[], '{"fundo":"#fff7f8","superficie":"#fffbfb","texto":"#2a1a1f","textoSuave":"#7a5a63","linha":"#f3dfe3","corCartao":"#ffffff","escuro":false,"faixa":"destaque","banner":"caixa","cartao":"preenchido","cantos":"redondos","tituloCaixa":"normal","tituloPeso":600,"tituloAlinhamento":"esquerda","nomeProduto":"normal","precoNaCor":false,"precoFonteTitulo":false,"fonte":"moderna","foto":"quadrado","colunas":4,"compraRapida":"passar-mouse"}'::jsonb, true, 90, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-joias', 'joias', 'Joias', 'Joias, semijoias, relógios, bijuterias', 'Escuro e sofisticado: serifa fina, títulos centralizados e muito espaço.', ARRAY['beleza', 'moda']::TEXT[], '{"fundo":"#0e0d0b","superficie":"#15130f","texto":"#f3ead8","textoSuave":"#b3a68c","linha":"#2c2820","corCartao":"#1b1914","escuro":true,"faixa":"preta","banner":"cheio","cartao":"simples","cantos":"retos","tituloCaixa":"normal","tituloPeso":500,"tituloAlinhamento":"centro","nomeProduto":"normal","precoNaCor":false,"precoFonteTitulo":false,"fonte":"elegante","foto":"quadrado","colunas":4,"compraRapida":"passar-mouse"}'::jsonb, true, 100, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-kids', 'kids', 'Kids', 'Infantil, brinquedos, enxoval', 'Colorido e redondo, cartões em tom pastel e títulos bem marcados.', ARRAY['infantil']::TEXT[], '{"fundo":"#fffdf5","superficie":"#ffffff","texto":"#1f2240","textoSuave":"#5b5f86","linha":"#e9e6ff","corCartao":"#f3f0ff","escuro":false,"faixa":"destaque","banner":"caixa","cartao":"preenchido","cantos":"redondos","tituloCaixa":"normal","tituloPeso":800,"tituloAlinhamento":"esquerda","nomeProduto":"normal","precoNaCor":false,"precoFonteTitulo":false,"fonte":"amigavel","foto":"quadrado","colunas":4,"compraRapida":"sempre"}'::jsonb, true, 110, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-casa', 'casa', 'Casa', 'Móveis, decoração, utilidades domésticas', 'Tons de areia, fotos em paisagem e banner de ponta a ponta.', ARRAY['casa']::TEXT[], '{"fundo":"#f6f2ec","superficie":"#fbf8f3","texto":"#2d2a26","textoSuave":"#6b645b","linha":"#e4ddd2","corCartao":"#ece5da","escuro":false,"faixa":"loja","banner":"cheio","cartao":"simples","cantos":"suaves","tituloCaixa":"normal","tituloPeso":500,"tituloAlinhamento":"esquerda","nomeProduto":"normal","precoNaCor":false,"precoFonteTitulo":false,"fonte":"moderna","foto":"paisagem","colunas":3,"compraRapida":"passar-mouse"}'::jsonb, true, 120, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-fitness', 'fitness', 'Fitness', 'Academia, suplementos, roupa esportiva', 'Escuro com detalhes fortes, títulos pesados em caixa alta e preço em destaque.', ARRAY['esporte']::TEXT[], '{"fundo":"#0c0c0d","superficie":"#141416","texto":"#f5f5f5","textoSuave":"#a1a1aa","linha":"#27272a","corCartao":"#18181b","escuro":true,"faixa":"destaque","banner":"cheio","cartao":"contorno","cantos":"retos","tituloCaixa":"alta","tituloPeso":400,"tituloAlinhamento":"esquerda","nomeProduto":"caixa-alta","precoNaCor":true,"precoFonteTitulo":false,"fonte":"impacto","foto":"quadrado","colunas":4,"compraRapida":"passar-mouse"}'::jsonb, true, 130, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-livraria', 'livraria', 'Livraria', 'Livros, papelaria, cursos', 'Fundo de papel, serifa clássica e capas em pé.', ARRAY['livros']::TEXT[], '{"fundo":"#f7f1e3","superficie":"#fbf7ec","texto":"#2b2418","textoSuave":"#6d6250","linha":"#e6dcc4","corCartao":"#efe6d0","escuro":false,"faixa":"loja","banner":"caixa","cartao":"simples","cantos":"retos","tituloCaixa":"normal","tituloPeso":600,"tituloAlinhamento":"esquerda","nomeProduto":"normal","precoNaCor":false,"precoFonteTitulo":false,"fonte":"elegante","foto":"alto","colunas":5,"compraRapida":"passar-mouse"}'::jsonb, true, 140, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-masculina', 'masculina', 'Moda Masculina', 'Moda masculina, barbearia, acessórios', 'Grafite e sóbrio: cantos retos, faixa preta e nomes em caixa alta.', ARRAY['moda']::TEXT[], '{"fundo":"#f3f4f5","superficie":"#ffffff","texto":"#1d2125","textoSuave":"#555c63","linha":"#d7dbdf","corCartao":"#e8eaec","escuro":false,"faixa":"preta","banner":"cheio","cartao":"simples","cantos":"retos","tituloCaixa":"alta","tituloPeso":700,"tituloAlinhamento":"esquerda","nomeProduto":"caixa-alta","precoNaCor":false,"precoFonteTitulo":false,"fonte":"moderna","foto":"retrato","colunas":4,"compraRapida":"passar-mouse"}'::jsonb, true, 150, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
INSERT INTO "Template" ("id", "chave", "nome", "paraQuem", "descricao", "segmentos", "receita", "ativo", "ordem", "acesso", "updatedAt") VALUES ('tpl-atacado', 'atacado', 'Atacado', 'Atacado, distribuidora, vendas B2B', 'Funcional: muitos produtos por linha, preço em destaque e compra rápida à vista.', ARRAY['atacado']::TEXT[], '{"fundo":"#f5f6f8","superficie":"#ffffff","texto":"#1a1d21","textoSuave":"#545b64","linha":"#dde1e6","corCartao":"#ffffff","escuro":false,"faixa":"destaque","banner":"caixa","cartao":"contorno","cantos":"suaves","tituloCaixa":"normal","tituloPeso":700,"tituloAlinhamento":"esquerda","nomeProduto":"normal","precoNaCor":true,"precoFonteTitulo":false,"fonte":"padrao","foto":"quadrado","colunas":6,"compraRapida":"sempre"}'::jsonb, true, 160, 'gratis', CURRENT_TIMESTAMP) ON CONFLICT ("chave") DO NOTHING;
