/*
 * Domínios de e-mail temporário/descartável. Quem cria loja com eles quase
 * sempre está atrás de teste grátis infinito ou de golpe: o e-mail some em
 * minutos e não há como avisar o lojista de nada (cobrança, pedido, senha).
 * Lista curada dos serviços mais usados; inclui subdomínios.
 */
const DOMINIOS = [
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.co.uk',
  '10minemail.com',
  '20minutemail.com',
  '33mail.com',
  'anonaddy.me',
  'burnermail.io',
  'byom.de',
  'cs.email',
  'dispostable.com',
  'dropmail.me',
  'emailondeck.com',
  'emailfake.com',
  'emailtemporal.org',
  'email-temp.com',
  'emltmp.com',
  'fakeinbox.com',
  'fakemail.net',
  'fakemailgenerator.com',
  'getairmail.com',
  'getnada.com',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'harakirimail.com',
  'inboxbear.com',
  'inboxkitten.com',
  'incognitomail.org',
  'jetable.org',
  'linshiyouxiang.net',
  'mail.tm',
  'mailcatch.com',
  'maildrop.cc',
  'mailinator.com',
  'mailinator.net',
  'mailinator2.com',
  'mailnesia.com',
  'mailpoof.com',
  'mailsac.com',
  'mailtemp.net',
  'mintemail.com',
  'mohmal.com',
  'moakt.com',
  'mytemp.email',
  'mytrashmail.com',
  'nada.email',
  'nowmymail.com',
  'one-time.email',
  'pokemail.net',
  'sharklasers.com',
  'spam4.me',
  'spambox.us',
  'spamgourmet.com',
  'tafmail.com',
  'temp-mail.io',
  'temp-mail.org',
  'tempail.com',
  'tempinbox.com',
  'tempm.com',
  'tempmail.com',
  'tempmail.dev',
  'tempmail.net',
  'tempmail.plus',
  'tempmailo.com',
  'tempr.email',
  'throwawaymail.com',
  'tmail.ws',
  'tmpmail.net',
  'tmpmail.org',
  'trashmail.com',
  'trashmail.de',
  'trashmail.net',
  'trashmail.ws',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'emailtemporario.com.br',
  'temp-mail.com.br',
  'emailna.co',
  'dcctb.com',
  'cuvox.de',
  'armyspy.com',
  'dayrep.com',
  'einrot.com',
  'fleckens.hu',
  'gustr.com',
  'jourrapide.com',
  'rhyta.com',
  'superrito.com',
  'teleworm.us',
  'mvrht.net',
  'vomoto.com',
  'xojxe.com',
  'zetmail.com',
  'mail7.io',
  'inboxes.com',
  'spamdecoy.net',
  'trbvm.com',
  'hidemail.de',
];

const SET = new Set(DOMINIOS);

/** true quando o domínio (ou um domínio pai) é de e-mail descartável */
export function emailDescartavel(email: string): boolean {
  const dominio = email.trim().toLowerCase().split('@')[1];
  if (!dominio) return false;
  const partes = dominio.split('.');
  for (let i = 0; i < partes.length - 1; i++) {
    if (SET.has(partes.slice(i).join('.'))) return true;
  }
  return false;
}
