-- AlterTable
ALTER TABLE "Address" DROP CONSTRAINT IF EXISTS "Address_customerId_key";

-- AlterTable
ALTER TABLE "Address" ADD COLUMN IF NOT EXISTS "label" TEXT;
ALTER TABLE "Address" ADD COLUMN IF NOT EXISTS "isDefault" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Address" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Address" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Address_customerId_idx" ON "Address"("customerId");
